### ISSUE TITLE
Improve error handling of the ckan API

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Registry-Refresher#12]
"If there was an error responding to your request, the dictionary will
contain an "error" key with details of the error instead of the "result"
key."

We should check for this happening, and print the contents of the error, instead of the current behaviour, which is a generic error message about the result key not existing.

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), and plans for the [Python Library](http://discuss.iatistandard.org/t/introducing-the-iati-python-library/720), the functionality of the Registry Refresher is to be migrated into a library module. 

This does not fall under maintenance or urgent additions, so will not be implemented.
