### ISSUE TITLE
Improve fault tolerance and error reporting in grab_urls.php

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Registry-Refresher#17]
This is particularly pertinent when the api_request() function does not obtain valid data via cURL:

PHP Notice:  Trying to get property of non-object in grab_urls.php on line 65
Notice: Trying to get property of non-object in grab_urls.php on line 65

PHP Warning:  Invalid argument supplied for foreach() in grab_urls.php on line 83
Warning: Invalid argument supplied for foreach() in grab_urls.php on line 83

This has caused issues with the nightly processes - eg on 20150408

**Comment by hayfield** [comment]
@dalepotter Is this still a problem that needs fixing?

**Comment by andylolz** [comment]
> Is this still a problem that needs fixing?

Yes, it is.

**Comment by akmiller01** [comment]
Fixed by https://github.com/IATI/IATI-Registry-Refresher/pull/31
