### ISSUE TITLE
Ckan metadata is not updating licenses

### ISSUE THREAD

**Issue by Ocre42** [IATI/IATI-Registry-Refresher#28]
As a result of some changes done in the metadata of the registry, it appears some of the metadata fields are not being updated properly. For instance: 
[Publish what you fund](https://www.iatiregistry.org/api/3/action/package_show?id=pwyf-998 ) shows their license_id as "odc-pddl", but [upon searching the ckan data on the dashboard](http://dashboard.iatistandard.org/stats/ckan.json) it shows it as "pddl".

**Comment by andylolz** [comment]
Looks like a registry bug or even a CKAN bug. See:
https://iatiregistry.org/api/3/action/package_search?fq=organization:pwyf

**Comment by Ocre42** [comment]
Curious, so the json files show the updated license ids but the api doesn't, I'll bring this up to the registry then.

**Comment by andylolz** [comment]
> so the json files show the updated license ids

Which JSON files do you mean?

**Comment by Ocre42** [comment]
![Screenshot from 2019-07-04 11-18-53](https://user-images.githubusercontent.com/7958292/60659625-c964af00-9e4d-11e9-9f0e-5a809f392ba0.png)
These files are what I mean, writing up the issue atm

**Comment by andylolz** [comment]
Ahh – so that link is a direct API call to:
https://iatiregistry.org/api/3/action/package_show?id=pwyf-998

![Screenshot 2019-07-04 at 11 24 44](https://user-images.githubusercontent.com/464193/60659860-5c054e00-9e4e-11e9-9032-bc7fbc2acefb.png)

**Comment by Ocre42** [comment]
So querying for all the files of an organisation appears to have some issues, whereas the individual package queries show the correct information? I'll look into it with a bit more detail once I get through some work.

**Comment by andylolz** [comment]
> So querying for all the files of an organisation appears to have some issues, whereas the individual package queries show the correct information?

I think queries to the `package_show` and `group_show` API endpoints show correct information. Queries to the `package_search` API endpoint seems to show stale information. E.g. here’s a query to `package_search` that searches for an individual package name. The license info in the response data is stale:
https://iatiregistry.org/api/3/action/package_search?fq=name:pwyf-998

I know that under the hood, [CKAN uses Solr for search](https://docs.ckan.org/en/2.8/maintaining/installing/install-from-source.html?highlight=solr#setup-solr). So I wonder if `package_search` responses are coming from Solr, and perhaps Solr caches aren’t set to update very frequently. But this is just speculation on my part.

**Comment by akmiller01** [comment]
Original issue appears resolved: http://dashboard.iatistandard.org/stats/ckan.json
