### ISSUE TITLE
Time the process

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Registry-Refresher#5]
I have a bit of code that I re-use in some scripts to tell us how long a process has taken. I think this application could do with having that info reported back.

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), and plans for the [Python Library](http://discuss.iatistandard.org/t/introducing-the-iati-python-library/720), the functionality of the Registry Refresher is to be migrated into a library module. 

This does not fall under maintenance or urgent additions, so will not be implemented.
