### ISSUE TITLE
Improved Logging

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Registry-Refresher#6]
I looked at checking what error code wget returned, and logging this https://github.com/Bjwebb/IATI-Registry-Refresher/commit/6ce400a6cee85df44a943c7b3ff5b3ef6f60feb0
I think we probably want to think about what other information we want to log (such as time taken #5) and how is best to go about it.

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), and plans for the [Python Library](http://discuss.iatistandard.org/t/introducing-the-iati-python-library/720), the functionality of the Registry Refresher is to be migrated into a library module. 

This does not fall under maintenance or urgent additions, so will not be implemented.
