### ISSUE TITLE
Wget will happily download some invalid urls

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Registry-Refresher#9]
Such as those missing the `http://` - this is an issue as they won't show up in my failed download list at https://gist.github.com/Bjwebb/6726204#file-errors even though many other software will quite rightly not download them.

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), and plans for the [Python Library](http://discuss.iatistandard.org/t/introducing-the-iati-python-library/720), the functionality of the Registry Refresher is to be migrated into a library module. 

This does not fall under maintenance or urgent additions, so will not be implemented.
